---
  - name: Check Sudo Password
    command: ls
    become: yes
    become_method: sudo

  - name: Update Homebrew
    homebrew: update_homebrew=yes

  - name: Tap Caskroom
    homebrew_tap: tap=caskroom/cask

  - name: Install Caskroom
    homebrew: name=brew-cask state=latest

  - name: Install Virtualbox
    homebrew_cask: name=virtualbox state=present
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications

  - name: Install Docker and Extras
    homebrew:
      name: "{{ item }}"
      state: latest
    with_items:
      - docker
      - docker-machine
      - docker-compose

  - name: Create resolver directory
    file: path=/etc/resolver state=directory mode=0755
    become: yes
    become_method: sudo

  - name: Create dev resolver file at /etc/resolver/dev
    template:
      src: resolver.conf
      dest: /etc/resolver/dev
      force: yes
    become: yes
    become_method: sudo

  - include: setup_nfs.yml

  - include: update_profile.yml

  - name: Create Docker Machine
    command: "{{ dev_env_dir }}/bin/dev machine create"
    args:
      creates: "~/.docker/machine/machines/{{ docker_machine_name }}/config.json"
